Vagrant.configure(2) do |config|
  hostnames = ["oomaster"]
  # hostnames = ["oomaster", "oodev"]

  hostnames.each do |hostname|
    config.vm.define "#{hostname}" do |subconfig|
      subconfig.vm.box = "box-cutter/centos72"
      subconfig.vm.box_version = "2.0.13"

      # Use the vagrant-cachier plugin, if installed, to cache downloaded packages
      if Vagrant.has_plugin?("vagrant-cachier")
        subconfig.cache.scope = :box
      end

      # subconfig.ssh.insert_key = false

      subconfig.vm.network "forwarded_port", guest: 3000, host: 9090  # Oneops GUI (rails)
      subconfig.vm.network "forwarded_port", guest: 8180, host: 9494  # OneOps CMS API
      subconfig.vm.network "forwarded_port", guest: 8080, host: 9191  # Oneops CMS Admin GUI
      subconfig.vm.network "forwarded_port", guest: 3001, host: 3003  # Jenkins
      subconfig.vm.network "forwarded_port", guest: 8161, host: 8166  # AMQ
      subconfig.vm.network "forwarded_port", guest: 5432, host: 9292  # PSQL

      subconfig.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "#{hostname}"]
        vb.customize ["modifyvm", :id, "--memory", 4096]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.gui = false
      end

      subconfig.vm.provision :shell, path: "provision/oo-prereqs.sh"

      if hostname == 'oodev'
        subconfig.vm.provision :shell, path: "provision/oo-setup-dev.sh", env: {"OO_VALIDATION" => "#{ENV['OO_VALIDATION']}"}
      else
        subconfig.vm.provision :shell, path: "provision/oo-setup.sh", env: {"OO_VALIDATION" => "#{ENV['OO_VALIDATION']}"}
      end

      subconfig.vm.provision :shell, path: "provision/inductor-setup.sh"

      subconfig.vm.synced_folder "#{ENV['HOME']}/OneOps/#{hostname}/", "/home/oneops/build/repos/",owner: "root",group: "root"
    end
  end
end
